### PR TITLE
Existential function calls

### PR DESCRIPTION
**Pull request by leeola**
Added an existential function to the styleguide.

This was commented on an internal PR by @gokmen, and i thought it would be good practice to include it _(or not)_ in the official styleguide. I take no credit :)

### CODE REVIEW

**Comment by leeola** [comment]
Not an important PR of course, but CCing for good measure.

cc @sinan @usirin

**Comment by sinan** [comment]
:+1:

**Comment by gokmen** [comment]
👍

**Comment by usirin** [comment]
:+1:

**Comment by sinan** [comment]
@cihangir prefers the unwanted way better but the difference here is that `?` also makes a type check it is not just for existential on functions. just an fyi.

**Comment by cihangir** [comment]
to me, in first place, there should not be any optional callback that is handled in function body.

**Comment by sinan** [comment]
`func (param, callback = ->)` like this?

**Comment by cihangir** [comment]
:+1:

**Pull request merged**
